# Generated by scripts/bootstrap.sh. Committed so every init is reproducible.
bucket = "marcusdunnca-tfstate-812642122818"
key    = "bootstrap/terraform.tfstate"
region = "ca-central-1"

encrypt = true

# S3-native state locking (OpenTofu >= 1.10). Replaces the legacy DynamoDB
# lock table, so there is no second resource to secure or pay for.
use_lockfile = true
