//! WebAuthn assertion verification and JWT issue/verify.
//!
//! There is no password. The only way in is a passkey whose public key is
//! already in this function's configuration — and there is no route that can add
//! one, except in the bootstrap mode in `register`, which exists only while that
//! configuration is empty and cannot coexist with any of the routes here.

use base64::engine::general_purpose::URL_SAFE_NO_PAD;
use base64::Engine as _;
use serde::{Deserialize, Serialize};
use trainer_core::clock;
use trainer_core::error::{Error, Result};
use trainer_core::keys;
use trainer_core::model::ChallengeItem;
use webauthn_rs::prelude::{PasskeyAuthentication, PublicKeyCredential};

use crate::state::AppState;

/// How long a session lasts. Thirty days, per spec.
///
/// There is no refresh, no revocation list and no server-side session record —
/// a stolen token is valid until it expires. That is an accepted trade for a
/// single-user personal tool where the alternative (a session table read on
/// every request) costs latency on a function competing for ten execution
/// slots. The mitigation that *does* exist is rotating the SSM parameter, which
/// invalidates every outstanding token at once.
const SESSION_SECS: i64 = 30 * 24 * 60 * 60;

/// A challenge is worthless after a minute. The window only has to cover a
/// human touching a fingerprint sensor.
const CHALLENGE_TTL_SECS: i64 = 60;

#[derive(Debug, Serialize, Deserialize)]
pub struct Claims {
    pub sub: String,
    pub iat: i64,
    pub exp: i64,
}

/// `POST /auth/challenge` response.
///
/// Deliberately *not* webauthn-rs's own `RequestChallengeResponse`. That type
/// serializes to the raw `PublicKeyCredentialRequestOptions` shape nested under
/// `publicKey`, and `web/src/lib/schemas.ts` expects a flattened envelope with
/// `timeoutMs` and a reduced `allowCredentials`. The client's
/// `toRequestOptions` reassembles the browser-facing structure itself, so this
/// is a translation rather than a passthrough.
///
/// Everything binary is base64url, which is what `Base64UrlSafeData` already
/// serializes to and what the client's `base64UrlToBytes` expects.
#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ChallengeResponse {
    pub challenge: String,
    pub rp_id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub timeout_ms: Option<u32>,
    pub allow_credentials: Vec<AllowCredentialDto>,
    pub user_verification: &'static str,
}

#[derive(Debug, Serialize)]
pub struct AllowCredentialDto {
    pub id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub transports: Option<Vec<String>>,
}

/// `POST /auth/verify` response.
///
/// `expiresAt` rather than a lifetime in days: the client stores the session in
/// localStorage and compares this against `Date.now()` to route to login before
/// making a call it knows will 401. A duration would require the client to
/// record when it received it, which it cannot do reliably across a reload.
#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct SessionResponse {
    pub token: String,
    pub expires_at: String,
}

/// Begin a login.
///
/// The challenge is generated by webauthn-rs (32 cryptographically random
/// bytes) rather than by this code, so that the bytes in the stored state and
/// the bytes the browser is asked to sign are the same object by construction.
///
/// The `PasskeyAuthentication` state is stored alongside it because it binds
/// the challenge to the credential set and to
/// `UserVerificationPolicy::Required`. Verifying against a state reconstructed
/// at verify time instead would mean the policy in force is whatever the code
/// says *now*, not what was promised when the challenge was issued.
pub async fn start_challenge(state: &AppState) -> Result<ChallengeResponse> {
    let (rcr, auth_state) = state
        .webauthn
        .start_passkey_authentication(state.credentials())
        .map_err(|e| {
            tracing::error!(error = ?e, "failed to start passkey authentication");
            Error::Unauthorized
        })?;

    let challenge_b64 = URL_SAFE_NO_PAD.encode(rcr.public_key.challenge.as_ref());

    let item = ChallengeItem {
        pk: keys::AUTH_PK.to_string(),
        sk: keys::challenge_sk(&challenge_b64),
        state: serde_json::to_string(&auth_state)?,
        expires_at: clock::unix_now() + CHALLENGE_TTL_SECS,
    };

    state.store.put_challenge(&item).await?;

    Ok(ChallengeResponse {
        challenge: challenge_b64,
        rp_id: rcr.public_key.rp_id,
        timeout_ms: rcr.public_key.timeout,
        allow_credentials: rcr
            .public_key
            .allow_credentials
            .iter()
            .map(|c| AllowCredentialDto {
                id: URL_SAFE_NO_PAD.encode(c.id.as_ref()),
                transports: c.transports.as_ref().map(|ts| {
                    ts.iter()
                        // Serialized via serde rather than `Debug` so the
                        // values are the spec's lowercase strings ("internal",
                        // "hybrid") that the browser accepts, not Rust variant
                        // names. A wrong transport hint is not fatal — the
                        // browser ignores unknown ones — but it silently
                        // narrows which authenticators are offered.
                        .filter_map(|t| serde_json::to_value(t).ok())
                        .filter_map(|v| v.as_str().map(str::to_owned))
                        .collect()
                }),
            })
            .collect(),
        // Always required. `start_passkey_authentication` issues the challenge
        // with `UserVerificationPolicy::Required` and `verify_assertion`
        // re-checks the flag, so anything else here would be a promise the rest
        // of the flow does not keep.
        user_verification: "required",
    })
}

/// Complete a login and mint a session token.
///
/// The ordering here is load-bearing:
///
/// 1. The challenge is **consumed first**, with a delete-and-return, before any
///    cryptography runs. Verifying first and deleting after leaves a window in
///    which a replayed assertion is accepted twice, and that window is exactly
///    as long as the signature check takes.
/// 2. Expiry is checked in this process, not left to DynamoDB TTL, which is a
///    background sweep documented as running within 48 hours. A 60-second
///    challenge enforced only by TTL is a 48-hour challenge.
/// 3. webauthn-rs then checks the signature, the origin (exact match — see the
///    note on `allow_subdomains` in `state.rs`), the RP ID hash, and the user
///    presence and user verification flags. UV is required because
///    `start_passkey_authentication` issues the challenge with
///    `UserVerificationPolicy::Required`; it is asserted again below so the
///    requirement is visible at the point it matters rather than being an
///    emergent property of a library default.
///
/// Every failure returns the same opaque `Unauthorized`. Distinguishing "no
/// such challenge" from "bad signature" from "expired" tells an attacker which
/// half of their attempt worked.
pub async fn verify_assertion(
    state: &AppState,
    credential: &PublicKeyCredential,
) -> Result<SessionResponse> {
    // The challenge is a field *inside* clientDataJSON, not a separate value
    // the browser hands us. Reading it from there rather than from a sibling
    // field in the request body means there is only one copy and no way for the
    // two to disagree.
    let challenge_b64 = extract_challenge(credential).ok_or(Error::Unauthorized)?;

    let Some(stored) = state.store.take_challenge(&challenge_b64).await? else {
        // Either never issued, already used, or reaped. All three are the same
        // answer to the caller.
        return Err(Error::Unauthorized);
    };

    if stored.expires_at < clock::unix_now() {
        return Err(Error::Unauthorized);
    }

    let auth_state: PasskeyAuthentication = serde_json::from_str(&stored.state)?;

    let result = state
        .webauthn
        .finish_passkey_authentication(credential, &auth_state)
        .map_err(|e| {
            // Logged at debug with the library's own error, which contains no
            // key material — only which check failed. Useful when a new phone
            // stops working; not useful to anyone who cannot read the logs.
            tracing::debug!(error = ?e, "assertion rejected");
            Error::Unauthorized
        })?;

    if !result.user_verified() {
        // Belt and braces over the library's policy. Without UV a passkey is a
        // single factor — possession of an unlocked phone — and this token is
        // valid for thirty days.
        tracing::debug!("assertion rejected: user verification flag not set");
        return Err(Error::Unauthorized);
    }

    // Deliberately no `Passkey::update_credential` call. Credentials are static
    // configuration here, so there is nowhere to write an updated counter, and
    // synced passkeys report zero forever anyway. See `load_access`.

    issue_token(state)
}

/// Recover the base64url challenge from `clientDataJSON`.
///
/// This is only used to *find the row*; it is not a security check. The
/// authoritative challenge comparison happens inside webauthn-rs against the
/// stored `PasskeyAuthentication`, so a caller who supplies a clientDataJSON
/// naming somebody else's challenge simply loads a state their signature will
/// not verify against — and, incidentally, consumes that challenge, which is a
/// denial of service against a login nobody else is performing.
fn extract_challenge(credential: &PublicKeyCredential) -> Option<String> {
    #[derive(Deserialize)]
    struct ClientData {
        challenge: String,
    }

    let raw: &[u8] = credential.response.client_data_json.as_ref();
    let parsed: ClientData = serde_json::from_slice(raw).ok()?;
    Some(parsed.challenge)
}

fn issue_token(state: &AppState) -> Result<SessionResponse> {
    let now = clock::unix_now();
    let exp = now + SESSION_SECS;
    let claims = Claims {
        // One user. The subject is a constant rather than a user id because
        // there is no user table; inventing one would imply a multi-user model
        // that nothing else in this app implements.
        sub: "owner".to_string(),
        iat: now,
        exp,
    };

    let token = jsonwebtoken::encode(
        &jsonwebtoken::Header::default(),
        &claims,
        &state.jwt_key.encoding,
    )
    .map_err(|e| {
        // `e` here is a jsonwebtoken error; its Display never contains the key.
        tracing::error!(error = %e, "failed to sign session token");
        Error::Unauthorized
    })?;

    Ok(SessionResponse {
        token,
        // Derived from the same `exp` that was signed into the claims, so the
        // client's pre-emptive expiry check and the server's verification agree
        // exactly. Two independently computed expiries would drift and produce
        // a window where the client believes it is signed in and every call
        // 401s.
        expires_at: clock::iso_at(exp),
    })
}

/// Verify the `Authorization: Bearer` header.
///
/// The algorithm is pinned to HS256 by `Validation::new`. That is the whole
/// point of constructing a `Validation` rather than accepting the default
/// behaviour of some other library: a verifier that honours the token's own
/// `alg` header accepts `alg: none`, and this is a symmetric key so it would
/// also accept a token signed with the *public* half of anything if asymmetric
/// algorithms were permitted.
///
/// Neither the token nor its claims are logged, at any level. A JWT in a log
/// line is a thirty-day credential in a log line.
pub fn require_session(state: &AppState, header: Option<&str>) -> Result<Claims> {
    let raw = header
        .and_then(|h| h.strip_prefix("Bearer "))
        .map(str::trim)
        .filter(|t| !t.is_empty())
        .ok_or(Error::Unauthorized)?;

    let mut validation = jsonwebtoken::Validation::new(jsonwebtoken::Algorithm::HS256);
    validation.set_required_spec_claims(&["exp"]);
    // No leeway. The default 60 seconds of clock skew allowance is a sensible
    // default for tokens issued by another system; here issuer and verifier are
    // the same function reading the same clock.
    validation.leeway = 0;

    let data = jsonwebtoken::decode::<Claims>(raw, &state.jwt_key.decoding, &validation)
        .map_err(|_| Error::Unauthorized)?;

    Ok(data.claims)
}
