#!/usr/bin/env bash
#
# One-time bootstrap, run by a human from a workstation with Identity Center
# admin credentials. Creates the state bucket, the GitHub OIDC trust anchor, and
# the two CI roles — the things CI itself must never be able to modify.
#
# Safe to re-run: after the first run it is just `init -reconfigure` + apply.
#
#   nix develop
#   aws sso login
#   ./scripts/bootstrap.sh
set -euo pipefail

cd "$(dirname "$0")/.."
REPO_ROOT="$PWD"
BOOTSTRAP_DIR="$REPO_ROOT/bootstrap"
INFRA_DIR="$REPO_ROOT/infra"

REGION="${AWS_REGION:-ca-central-1}"

# This machine also has a dozen work AWS profiles configured. Applying
# admin-level IAM changes to one of those would be a genuinely bad afternoon,
# so the target account is asserted rather than merely defaulted.
EXPECTED_ACCOUNT_ID="812642122818"

# --------------------------------------------------------------------------
# Confirm we are pointed at the right account.
# --------------------------------------------------------------------------
echo "==> Verifying AWS identity"
if ! IDENTITY="$(aws sts get-caller-identity --output json 2>&1)"; then
  echo "Could not reach AWS. Run 'aws sso login' first." >&2
  echo "$IDENTITY" >&2
  exit 1
fi

ACCOUNT_ID="$(echo "$IDENTITY" | jq -r .Account)"
CALLER_ARN="$(echo "$IDENTITY" | jq -r .Arn)"

echo "    Account: $ACCOUNT_ID"
echo "    Caller:  $CALLER_ARN"
echo "    Region:  $REGION"

if [ "$ACCOUNT_ID" != "$EXPECTED_ACCOUNT_ID" ]; then
  cat >&2 <<EOF

REFUSING TO CONTINUE.

  Expected account: ${EXPECTED_ACCOUNT_ID}
  Actually authenticated to: ${ACCOUNT_ID} (${CALLER_ARN})

Your shell is pointed at the wrong AWS account. Run this from inside
'nix develop' (which sets AWS_PROFILE=marcusdunnca), or set the profile
explicitly:

  AWS_PROFILE=marcusdunnca aws sso login
EOF
  exit 1
fi

echo
read -r -p "Apply bootstrap to account ${ACCOUNT_ID}? [y/N] " confirm
[ "$confirm" = "y" ] || { echo "Aborted."; exit 1; }

STATE_BUCKET="marcusdunnca-tfstate-${ACCOUNT_ID}"

write_backend_hcl() {
  local dir="$1" key="$2"
  cat > "${dir}/backend.hcl" <<EOF
# Generated by scripts/bootstrap.sh. Committed so every init is reproducible.
bucket = "${STATE_BUCKET}"
key    = "${key}"
region = "${REGION}"

encrypt = true

# S3-native state locking (OpenTofu >= 1.10). Replaces the legacy DynamoDB
# lock table, so there is no second resource to secure or pay for.
use_lockfile = true
EOF
  echo "    Wrote ${dir#"$REPO_ROOT"/}/backend.hcl"
}

cd "$BOOTSTRAP_DIR"

if [ -f backend.hcl ] && aws s3api head-bucket --bucket "$STATE_BUCKET" >/dev/null 2>&1; then
  # --------------------------------------------------------------------------
  # Normal path: bucket and backend config already exist.
  # --------------------------------------------------------------------------
  echo "==> State bucket exists; initialising against S3 backend"
  # -lockfile=readonly makes init FAIL rather than silently adding a provider
  # that appeared in state but not in the committed lockfile. That is the
  # detection for state-injected providers: this module is applied by a human
  # holding AdministratorAccess, and init/plan execute provider binaries before
  # the apply prompt is ever shown.
  tofu init -input=false -reconfigure -lockfile=readonly -backend-config=backend.hcl
  tofu apply -input=false
else
  # --------------------------------------------------------------------------
  # First run: the bucket that will hold this state does not exist yet, so the
  # S3 backend cannot be initialised. Apply against local state, then migrate.
  # --------------------------------------------------------------------------
  echo "==> First run: applying with local state (bucket does not exist yet)"
  mv backend.tf backend.tf.disabled
  # Make sure the backend block comes back even if apply fails.
  trap 'mv -f "$BOOTSTRAP_DIR/backend.tf.disabled" "$BOOTSTRAP_DIR/backend.tf" 2>/dev/null || true' EXIT

  tofu init -input=false
  tofu apply -input=false

  echo "==> Generating backend configuration"
  write_backend_hcl "$BOOTSTRAP_DIR" "bootstrap/terraform.tfstate"
  write_backend_hcl "$INFRA_DIR" "infra/terraform.tfstate"

  mv -f backend.tf.disabled backend.tf
  trap - EXIT

  echo "==> Migrating bootstrap state into s3://${STATE_BUCKET}"
  tofu init -input=false -migrate-state -force-copy -backend-config=backend.hcl

  echo "==> Removing local state copies (now authoritative in S3)"
  rm -f terraform.tfstate terraform.tfstate.backup
fi

# Ensure infra's backend config exists even on the re-run path.
[ -f "${INFRA_DIR}/backend.hcl" ] || write_backend_hcl "$INFRA_DIR" "infra/terraform.tfstate"

PLAN_ROLE_ARN="$(tofu output -raw plan_role_arn)"
APPLY_ROLE_ARN="$(tofu output -raw apply_role_arn)"

cat <<EOF

==> Bootstrap complete.

    Account:     ${ACCOUNT_ID}
    State:       s3://${STATE_BUCKET}
    Plan role:   ${PLAN_ROLE_ARN}
    Apply role:  ${APPLY_ROLE_ARN}

Next: ./scripts/github-setup.sh
EOF
